[buildpack]
id = "neeto-deploy/sqlite"
version = "0.1.0"
name = "NeetoDeploy SQLite Buildpack"
description = "A Cloud Native Buildpack that installs sqlite3 for use in Rails and Node.js apps."

[metadata]
homepage = "https://github.com/bigbinary/neeto-deploy-sqlite-buildpack"
authors = ["NeetoDeploy Team <support@neeto.com>"]

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
